testClienteFactura/testClienteFactura/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using testClientBillBLL;
using Clients = testClientBillModels.Clients;
namespace testClienteFactura.Controllers
{
    public class ClientsController : Controller
    {
        private testClientBillBLL.Clients _ClientBll = new testClientBillBLL.Clients();

        //********************************************
        //          Show Clients List
        //********************************************
        public ActionResult List()
        {
            return View(_ClientBll.GetClientList(0));
        }

        //********************************************
        //          Show Clients Add Form
        //********************************************
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        //********************************************
        //              Add Client
        //********************************************
        [HttpPost]
        public ActionResult AddClient(Clients client)
        {
            client.ClientCreated = DateTime.Today;
            client.ClientLastAccess = DateTime.Today;
            _ClientBll.RegisterClient(client);
            return View("List",_ClientBll.GetClientList(0));
        }

        public class ClientMock 
        {
            public string ClientFirstName { get; set; }
            public string ClientLastName { get; set; }
            public string ClientEmailAddress { get; set; }
            public string ClientPhone { get; set; }
            public string ClientAddress { get; set; }
            
        }

        [HttpPost]
        public JsonResult AddNewClient(string[] client)
        {

            testClientBillModels.Clients newClient = new Clients();
            newClient.ClientFirstName = client[0].ToUpper();
            newClient.ClientLastName = client[1].ToUpper();
            newClient.ClientEmail = client[2].ToUpper();
            newClient.ClientPhone = client[4];
            newClient.ClientAddress = client[3].ToUpper();
            newClient.ClientCreated = DateTime.Today;
            newClient.ClientLastAccess = DateTime.Today;
            bool result = _ClientBll.RegisterClient(newClient);
            return Json(result,JsonRequestBehavior.AllowGet);
        }

        //********************************************
        //          Show Clients Edit Form
        //********************************************
        [HttpGet]
        public ActionResult Edit(Clients client)
        {
            return View(client);
        }

        //********************************************
        //          Edit Client
        //********************************************
        [HttpPost]
        public ActionResult ChangeClient(Clients client)
        {
            if (client != null)
            {
                client.ClientLastAccess = DateTime.Today;
                _ClientBll.ChangeClient(client);
            }
            return View("List",_ClientBll.GetClientList(0));
        }

        //********************************************
        //          Delete Client
        //********************************************
      
        [HttpGet]
        public ActionResult Delete(int idClient)
        {
            if (idClient!=0)_ClientBll.RemoveClient(idClient);
            return View("List",_ClientBll.GetClientList(0));
        }

    }
}

testClienteFactura/testClienteFactura/Views/Clients/Add.cshtml
@model testClientBillModels.Clients

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm("AddClient", "Clients", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Clients</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClientFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group col-md-offset-2 col-md-10">
            <div id="edit-buttons">
                <button type="submit" class="btn btn-success" value="AddBill">Save</button>
                <button type="reset" class="btn btn-default">Reset</button>
                <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("List", "Clients")';">Go Back</button>
            </div>
        </div>
    </div>
}

testClienteFactura/testClienteFactura/Views/Clients/Edit.cshtml
@model testClientBillModels.Clients

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("ChangeClient", "Clients", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Client: @Model.ClientFirstName, @Model.ClientLastName </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdClient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdClient, new { htmlAttributes = new {
               @class = "form-control" ,
               @readonly = "readonly",
           } })
                @Html.ValidationMessageFor(model => model.IdClient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientCreated, new { htmlAttributes = new {
               @class = "form-control" ,
               @readonly = "readonly",
           } })
                @Html.ValidationMessageFor(model => model.ClientCreated, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ClientLastAccess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientLastAccess, new
                {
                    htmlAttributes = new
                    {
                        @class = "form-control",
                        @readonly = "readonly",
                        @value = DateTime.Today
                    }
                })
                @Html.ValidationMessageFor(model => model.ClientLastAccess, "", new {@class = "text-danger"})
            </div>
            <br/><br /><br />

            <div class="form-group col-md-offset-2 col-md-10">
                <div id="edit-buttons">
                    <button type="submit"  class="btn btn-success" value="AddBill">Save</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                    <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("List", "Clients")';">Go Back</button>
                </div>
            </div>
        </div>

        
    </div>
}

testClienteFactura/testClienteFactura/Views/Clients/List.cshtml
@using testClientBillModels
@model List<testClientBillModels.Clients>

@{
    ViewBag.Title = "List";
    
}

@section scripts{
    
}
<div class="container">
    <div class="row">
        <div class="col-ld-12">
            <h2>Clients</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group btn-group" id="btn-table">
                <button type="button" class="btn btn-success" onclick="location.href = '@Url.Action("Add", "Clients")';">New</button>
                <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Home")';">Go Back</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-ld-12">
            <table class="table table-striped table-bordered table-list" id="ClientsDataTable">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Address</th>
                        <th>Created</th>
                        <th>Last Access</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (testClientBillModels.Clients client in Model)
                    {
                        <tr>
                            <td>@client.ClientFirstName @client.ClientLastName</td>
                            <td>@client.ClientEmail</td>
                            <td>@client.ClientPhone</td>
                            <td>@client.ClientAddress</td>
                            <td>@client.ClientCreatedFormated</td>
                            <td>@client.ClientLastAccessFormated</td>
                            <td>
                                <a title="Edit" href="@Url.Action("Edit", "Clients", client)" aria-label="Edit" class="btn btn-default">
                                    <em class="fa fa-pencil"></em>
                                </a>
                                <button type="button" class="btn btn-danger"
                                        data-toggle="modal" data-target="#deleteModal" id="modalOpen" name="@client.IdClient">
                                    <em class="fa fa-trash"></em>
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="form-group btn-group" id="btn-table">
                    <button type="button" class="btn btn-success" onclick="location.href = '@Url.Action("Add", "Clients")';">New</button>
                    <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Home")';">Go Back</button>
                </div>
            </div>
        </div>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Are you sure you want to delete?</h4>
            </div>
            <div class="modal-body">
                <p>This client owns this bills:</p>
                <table class="table table-striped table-bordered table-list" id="BillsModalDataTable">
                    <thead>
                    <tr>
                        <th class="hidden">ClientId</th>
                        <th>Client Name</th>
                        <th>Bill Number</th>
                        <th>Date</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody id="modalTbody"></tbody>
                </table>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="modalDeleteBtn">Delete</button>
                <button type="button" class="btn btn-default" data-dismiss="modal" id="modalCloseBtn">Close</button>
            </div>
        </div>
    </div>
</div>