testClienteFactura/testClienteFactura/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using testClientBillModels;
using testClientBillBLL;
using Users = testClientBillModels.Users;

namespace testClienteFactura.Controllers
{
    public class LoginController : Controller
    {
        private testClientBillBLL.Login _LoginBll = new testClientBillBLL.Login();

        // GET: Login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Users user)
        {
            if (ModelState.IsValid)
            {
                if (_LoginBll.ValidateUserCredentials(user.UserUsername, user.UserPassword))
                {
                    FormsAuthentication.SetAuthCookie(user.UserUsername, user.RememberMe);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Login data is incorrect!");
                }

            }
            return View(user);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Login");
        }
    }
}

testClienteFactura/testClienteFactura/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace testClienteFactura.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Users()
        {
            return View();
        }


        public ActionResult Register()
        {
            return View();
        }
    }
}

testClienteFactura/testClienteFactura/Views/Login/Login.cshtml
@model testClientBillModels.Users
@{
    ViewBag.Title = "Login";
}
<html>
<head>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/fonts/fontawesome-webfont.woff")" rel="stylesheet" type="text/css">
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-md-offset-4">
                <br /><br />
                <div class="account-wall">
                    <i class="fa fa-user" aria-hidden="true" id="loginLogo"></i>
                    @using (Html.BeginForm("Login", "Login", FormMethod.Post, new {@class = "form-signin"}))
                    {
                        @Html.ValidationSummary(true, "", new {@class = "alert alert-danger"})
                        @Html.TextBoxFor(x => x.UserUsername, new {@class = "form-control", @placeholder = "Username", required = "required"})
                        @Html.TextBoxFor(x => x.UserPassword, new {@class = "form-control", @type = "password", @placeholder = "Password", required = "required"})
                        <div class="login-btn text-center">
                            <button class="btn btn-lg btn-primary btn-block" type="submit">
                                Sign in
                            </button>
                            <label class="checkbox pull-left">
                                <input type="checkbox" value="remember-me">
                                Remember me
                            </label>    
                        </div>
                    }

                    <div class="row container text-center">
                        <br/>
                        @Html.ActionLink("Register", "Register", "Users")
                    </div>
                </div>

            </div>
        </div>
    </div>

</body>